user_analytics:
  outputs:
    dev:
      type: duckdb
      path: 'data.duckdb'
      extensions:
        - httpfs
        - parquet
    prod:
      type: duckdb
      path: 'data.duckdb'
      extensions:
        - httpfs
        - parquet
  target: dev