version: 2

sources:
  - name: raw_data
    description: Raw user analytics data
    schema: raw_data
    tables:
      - name: users
        description: User information
        columns:
          - name: user_id
            description: Unique user identifier
            tests:
              - not_null
              - unique
          - name: name
            description: User full name
          - name: email
            description: User email address
          - name: age
            description: User age
          - name: location
            description: User location
          - name: created_at
            description: User registration date

      - name: transactions
        description: Transaction information
        columns:
          - name: transaction_id
            description: Unique transaction identifier
            tests:
              - not_null
              - unique
          - name: user_id
            description: User who made the transaction
            tests:
              - not_null
              - relationships:
                  to: source('raw_data', 'users')
                  field: user_id
          - name: amount
            description: Transaction amount
          - name: product_category
            description: Product category
          - name: created_at
            description: Transaction timestamp
            tests:
              - not_null