version: 2

models:
  - name: dim_users
    description: "User dimension table with behavioral metrics and segmentation"
    columns:
      - name: user_id
        description: "Unique identifier for each user"
        tests:
          - unique
          - not_null
      - name: user_created_at
        description: "Date when the user was created"
        tests:
          - not_null
      - name: total_transactions
        description: "Total number of transactions for this user"
      - name: first_transaction_at
        description: "Date of user's first transaction"
      - name: last_transaction_at
        description: "Date of user's most recent transaction"
      - name: user_segment
        description: "User behavior segment based on transaction patterns"
      - name: days_to_first_transaction
        description: "Number of days between signup and first transaction"

  - name: fct_transactions
    description: "Transaction fact table with user context and derived metrics"
    columns:
      - name: transaction_id
        description: "Unique identifier for each transaction"
        tests:
          - unique
          - not_null
      - name: user_id
        description: "Foreign key to users"
        tests:
          - not_null
      - name: transaction_created_at
        description: "Date when the transaction occurred"
        tests:
          - not_null
      - name: user_created_at
        description: "Date when the user signed up"
      - name: transaction_year
        description: "Year the transaction occurred"
      - name: transaction_month
        description: "Month the transaction occurred"
      - name: transaction_day_of_week
        description: "Day of week (0=Sunday, 6=Saturday)"
      - name: days_since_signup
        description: "Days between user signup and this transaction"
      - name: user_transaction_number
        description: "Sequential number of this transaction for the user"
      - name: transaction_type
        description: "Classification of transaction (First, Early, Recurring)"